Document: meebible
Title: Debian meebible Manual
Author: <insert document author here>
Abstract: This manual describes what meebible is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/meebible/meebible.sgml.gz

Format: postscript
Files: /usr/share/doc/meebible/meebible.ps.gz

Format: text
Files: /usr/share/doc/meebible/meebible.text.gz

Format: HTML
Index: /usr/share/doc/meebible/html/index.html
Files: /usr/share/doc/meebible/html/*.html
